/* 9 test tanıtım sayfasının içeriği. Her sayfa iki dili de HTML içinde taşır;
   i18n.js yalnızca doğru dildeki bloğu gösterir. */
export const TESTS = [
{ id:'sleep', slug:'sleep', icon:'moon', bg:'#e0f2fe', fg:'#0369a1',
  en:{ name:'Sleep Quality',
    title:'Sleep Quality Self-Assessment — ShenTechin MED',
    desc:'A free 25-question self-assessment of your sleep schedule, environment and bedtime habits. Educational only, not a diagnosis.',
    lede:'Sleep problems rarely have a single cause. More often they are the sum of a bedtime that moves around, a room that is too bright or too warm, and a few habits in the last hour of the day. This assessment walks through those one at a time.',
    measures:['How many hours you sleep and how steady the schedule is from night to night','How long it takes to fall asleep, and whether you stay asleep once you do','Daytime function — how rested you wake and where sleepiness turns up','The bedroom and the last hour: light, noise, bedding, caffeine, screens','Signs a screening tool would flag: snoring, breathing pauses, restless legs'],
    who:'Anyone who sleeps enough hours but still wakes up tired, has a bedtime that drifts later each week, or wants a structured way to see which habit is doing the most damage.',
    faq:[{q:'Can this tell me if I have insomnia or sleep apnoea?',a:'No. Both are clinical diagnoses that need a doctor, and sleep apnoea in particular is usually confirmed with a sleep study. What this assessment can do is show you whether the signs are present often enough to be worth raising.'},
         {q:'How long does it take?',a:'The full assessment is 25 questions and takes about six minutes. If you are short of time there is also a 10-question version, but the report is thinner because there is less to work with.'},
         {q:'Are my answers stored anywhere?',a:'Only in your own browser, so you can leave and come back. Nothing is sent to us and there is no account to create.'}]},
  tr:{ name:'Uyku Kalitesi',
    title:'Uyku Kalitesi Öz-Değerlendirmesi — ShenTechin MED',
    desc:'Uyku düzeninizi, ortamınızı ve yatma saati alışkanlıklarınızı ölçen ücretsiz 25 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır, teşhis değildir.',
    lede:'Uyku sorunlarının tek bir nedeni nadiren olur. Çoğu zaman kayan bir yatış saatinin, fazla aydınlık ya da sıcak bir odanın ve günün son saatindeki birkaç alışkanlığın toplamıdır. Bu değerlendirme bunların üzerinden tek tek geçiyor.',
    measures:['Kaç saat uyuduğunuzu ve düzenin geceden geceye ne kadar sabit olduğunu','Uykuya dalmanın ne kadar sürdüğünü ve daldıktan sonra uykuda kalıp kalmadığınızı','Gündüz işlevini — ne kadar dinç uyandığınızı ve uykululuğun nerede ortaya çıktığını','Yatak odasını ve son saati: ışık, gürültü, yatak, kafein, ekran','Bir tarama aracının işaretleyeceği belirtileri: horlama, nefes durması, huzursuz bacak'],
    who:'Yeterli saat uyuduğu hâlde yorgun uyanan, yatış saati her hafta biraz daha geriye kayan ya da hangi alışkanlığın en çok zarar verdiğini düzenli biçimde görmek isteyen herkes.',
    faq:[{q:'Bu test uykusuzluk (insomnia) veya uyku apnesi olduğumu söyler mi?',a:'Hayır. İkisi de hekim gerektiren klinik tanılardır; özellikle uyku apnesi genellikle uyku testiyle doğrulanır. Bu değerlendirmenin yapabileceği şey, işaretlerin dile getirmeye değecek sıklıkta olup olmadığını göstermektir.'},
         {q:'Ne kadar sürüyor?',a:'Tam değerlendirme 25 soru ve yaklaşık altı dakika sürüyor. Vaktiniz yoksa 10 soruluk bir sürüm de var; ama elde daha az veri olduğu için rapor da daha ince oluyor.'},
         {q:'Cevaplarım bir yerde saklanıyor mu?',a:'Yalnızca kendi tarayıcınızda; böylece ara verip geri dönebiliyorsunuz. Bize hiçbir şey gönderilmiyor ve açılacak bir hesap yok.'}]}},

{ id:'skin', slug:'skin', icon:'sparkles', bg:'#fce7f3', fg:'#be185d',
  en:{ name:'Skin Profile',
    title:'Skin Profile Self-Assessment — ShenTechin MED',
    desc:'A free 25-question self-assessment of your skin type, sun protection and daily routine. Educational only, not a dermatological diagnosis.',
    lede:'Most skincare advice is written for a skin type you may not have. Before choosing products it helps to know how your skin actually behaves — how it reacts to sun, how quickly it gets oily, and how it responds to being touched, washed and covered.',
    measures:['Sun protection — how often, how consistently, and through which seasons','Cleansing and barrier care: what you wash with and what you put back','Habits that irritate — picking, over-exfoliating, sleeping in makeup, friction','What reaches the skin from the inside: sleep, tobacco, diet, stress','Signs and follow-up: what is not settling, and whether you would spot a mole changing'],
    who:'Anyone unsure whether their skin is dry or dehydrated, oily or over-cleansed, and anyone who keeps buying products without a clear picture of what their skin actually needs.',
    faq:[{q:'Will this tell me which products to buy?',a:'No, and be sceptical of anything that claims it will from a questionnaire. It gives you a clearer description of how your skin behaves, which makes product advice easier to filter.'},
         {q:'I have acne or rosacea. Is this useful?',a:'As a habit check, yes. As a treatment guide, no — both respond to specific medical treatment, and a dermatologist will get you there far faster than a routine change.'},
         {q:'Does it account for skin tone?',a:'Only indirectly, through how your skin reacts to sun exposure. It is not a substitute for advice tailored to your skin tone.'}]},
  tr:{ name:'Cilt Profili',
    title:'Cilt Profili Öz-Değerlendirmesi — ShenTechin MED',
    desc:'Cilt tipinizi, güneşten korunmanızı ve günlük rutininizi ölçen ücretsiz 25 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır, dermatolojik teşhis değildir.',
    lede:'Cilt bakımı önerilerinin çoğu, sizde olmayan bir cilt tipi için yazılmıştır. Ürün seçmeden önce cildinizin gerçekte nasıl davrandığını bilmek işe yarar — güneşe nasıl tepki verdiğini, ne kadar çabuk yağlandığını, dokunulunca, yıkanınca ve kapatılınca ne yaptığını.',
    measures:['Güneş korumasını — ne sıklıkla, ne kadar düzenli ve hangi mevsimlerde','Temizlik ve bariyer bakımını: neyle yıkadığınızı ve yerine ne koyduğunuzu','Tahriş eden alışkanlıkları — kurcalama, aşırı peeling, makyajla uyuma, sürtünme','Cilde içeriden ulaşanları: uyku, tütün, beslenme, stres','İşaretleri ve takibi: geçmeyen ne var ve bir bendeki değişimi fark eder miydiniz'],
    who:'Cildinin kuru mu susuz mu, yağlı mı aşırı temizlenmiş mi olduğundan emin olmayan ve cildinin gerçekte neye ihtiyacı olduğunu bilmeden ürün almayı sürdüren herkes.',
    faq:[{q:'Hangi ürünleri alacağımı söyleyecek mi?',a:'Hayır — ve bir anketten yola çıkıp bunu vaat eden her şeye kuşkuyla yaklaşın. Size cildinizin nasıl davrandığına dair daha net bir tarif verir; bu da ürün önerilerini elemeyi kolaylaştırır.'},
         {q:'Aknem veya rozasem var. İşe yarar mı?',a:'Alışkanlık kontrolü olarak evet. Tedavi rehberi olarak hayır — ikisi de belirli tıbbi tedaviye yanıt verir ve bir dermatolog sizi oraya rutin değişikliğinden çok daha hızlı götürür.'},
         {q:'Cilt tonunu hesaba katıyor mu?',a:'Yalnızca dolaylı olarak, cildinizin güneşe verdiği tepki üzerinden. Cilt tonunuza özel bir önerinin yerini tutmaz.'}]}},

{ id:'diet', slug:'diet', icon:'leaf', bg:'#dcfce7', fg:'#15803d',
  en:{ name:'Nutrition Habits',
    title:'Nutrition Habits Self-Assessment — ShenTechin MED',
    desc:'A free 25-question self-assessment of meal regularity, food choices and eating patterns. Educational only, not dietary advice.',
    lede:'This is not a diet test and it will not calculate anything about your body. It asks about the structure around your eating — when you eat, what usually ends up on the plate, and what tends to drive the decision.',
    measures:['Meal rhythm — how regular your meals are and what the evening has to compensate for','Plant foods: fruit, vegetables, pulses, wholegrains, and how varied they are','Protein and fat quality — fish, olive oil, red and processed meat','Ultra-processed food, sugary drinks, and how much of the week is bought ready-made','Salt, alcohol and fluids — including the sodium that arrives hidden in packaging'],
    who:'Anyone whose eating has drifted into whatever is quickest, anyone stuck in a start-a-diet-then-abandon-it loop, and anyone who wants to find the one habit worth fixing first.',
    faq:[{q:'Does it calculate calories or BMI?',a:'No. It does not ask for your weight, height or intake, and it does not estimate anything about your body. It only looks at habits.'},
         {q:'Can it detect a food intolerance?',a:'No. Intolerances and allergies need proper testing — self-diagnosis here leads people to cut out foods unnecessarily.'},
         {q:'Should I see a dietitian instead?',a:'If you have a medical condition, a history of disordered eating, or repeated cycles of losing and regaining weight, then yes — a dietitian will help far more than any online assessment.'}]},
  tr:{ name:'Beslenme Alışkanlıkları',
    title:'Beslenme Alışkanlıkları Öz-Değerlendirmesi — ShenTechin MED',
    desc:'Öğün düzeninizi, besin tercihlerinizi ve yeme örüntünüzü ölçen ücretsiz 25 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır, diyet önerisi değildir.',
    lede:'Bu bir diyet testi değildir ve bedeninizle ilgili hiçbir hesap yapmaz. Yemenizin etrafındaki düzeni sorar — ne zaman yediğinizi, tabakta genellikle ne olduğunu ve kararı çoğunlukla neyin verdiğini.',
    measures:['Öğün ritmini — öğünlerinizin ne kadar düzenli olduğunu ve akşamın neyi telafi ettiğini','Bitkisel gıdaları: meyve, sebze, baklagil, tam tahıl ve bunların çeşitliliğini','Protein ve yağ kalitesini — balık, zeytinyağı, kırmızı ve işlenmiş et','Ultra-işlenmiş gıdayı, şekerli içecekleri ve haftanın ne kadarının hazır alındığını','Tuz, alkol ve sıvıyı — paketin içinde gizli gelen sodyum dâhil'],
    who:'Yemeği "en hızlı ne varsa" hâline gelmiş olanlar, diyete başlayıp bırakma döngüsüne sıkışanlar ve önce hangi alışkanlığı düzeltmesi gerektiğini bulmak isteyenler.',
    faq:[{q:'Kalori veya VKİ hesaplıyor mu?',a:'Hayır. Kilonuzu, boyunuzu ya da aldığınız miktarı sormuyor ve bedeninizle ilgili hiçbir tahmin yapmıyor. Yalnızca alışkanlıklara bakıyor.'},
         {q:'Besin intoleransı saptayabilir mi?',a:'Hayır. İntoleranslar ve alerjiler düzgün testlerle saptanır — buradan yola çıkarak kendi kendine tanı koymak, insanların gereksiz yere besin kesmesine yol açıyor.'},
         {q:'Bunun yerine diyetisyene mi gitmeliyim?',a:'Bir sağlık sorununuz, düzensiz yeme geçmişiniz ya da tekrarlayan kilo verip alma döngüleriniz varsa evet — bir diyetisyen her çevrimiçi değerlendirmeden çok daha faydalı olur.'}]}},

{ id:'stress', slug:'stress', icon:'brain', bg:'#fef3c7', fg:'#b45309',
  en:{ name:'Stress Load',
    title:'Stress Load Self-Assessment — ShenTechin MED',
    desc:'A free 25-question self-assessment of daily pressure, physical stress signs and recovery capacity. Educational only, not a mental health diagnosis.',
    lede:'Stress becomes a problem less because of how much arrives and more because of how little recovery gets in between. This assessment looks at both sides: the load you carry and what you have in place to offset it.',
    measures:['Perceived load — how unpredictable and overloaded the past month has felt','Control and predictability: how much of it you can actually steer','Physical signs — jaw, shoulders, gut, sleep, heart rate, appetite','Recovery: whether you get genuinely off-duty time, and what you do with it','Support and coping — who you can call, and what you reach for instead'],
    who:'Anyone who feels permanently switched on, anyone whose body has started keeping the score, and anyone wanting a structured look before deciding whether to get help.',
    faq:[{q:'Is this a depression or anxiety screening?',a:'No. Those are specific clinical screenings, and this is not one of them. If your answers concern you, that is a good reason to speak to a GP or psychologist rather than to retake the test.'},
         {q:'I scored badly. What now?',a:'Start by treating it as information rather than a verdict. If pressure has been high for months, if you have panic attacks, or if your mood has been consistently low, please talk to a professional.'},
         {q:'Can stress really cause physical symptoms?',a:'Yes — muscle tension, jaw clenching, disturbed sleep and digestive upset are all common. But physical symptoms should never be assumed to be "just stress" without a doctor ruling out other causes.'}]},
  tr:{ name:'Stres Yükü',
    title:'Stres Yükü Öz-Değerlendirmesi — ShenTechin MED',
    desc:'Günlük baskıyı, fiziksel stres işaretlerini ve toparlanma kapasitesini ölçen ücretsiz 25 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır, ruh sağlığı teşhisi değildir.',
    lede:'Stres, ne kadar geldiğinden çok arasına ne kadar az toparlanma girdiği için sorun hâline gelir. Bu değerlendirme iki tarafa da bakıyor: taşıdığınız yüke ve onu dengelemek için elinizde ne olduğuna.',
    measures:['Algılanan yükü — son bir ayın ne kadar öngörülemez ve dolu hissettirdiğini','Kontrol ve öngörülebilirliği: ne kadarını gerçekten yönlendirebildiğinizi','Bedensel işaretleri — çene, omuz, mide, uyku, kalp hızı, iştah','Toparlanmayı: gerçekten görev dışı zamanınız oluyor mu ve onunla ne yapıyorsunuz','Destek ve başa çıkmayı — kimi arayabildiğinizi ve onun yerine neye uzandığınızı'],
    who:'Sürekli "açık" hisseden, bedeni hesabı tutmaya başlamış olan ve destek alıp almayacağına karar vermeden önce düzenli bir bakış isteyen herkes.',
    faq:[{q:'Bu bir depresyon veya anksiyete taraması mı?',a:'Hayır. Onlar belirli klinik taramalardır, bu onlardan biri değildir. Cevaplarınız sizi endişelendiriyorsa, bu testi tekrar çözmek yerine bir hekime ya da psikoloğa danışmak için iyi bir gerekçedir.'},
         {q:'Düşük puan aldım, şimdi ne olacak?',a:'Bunu bir hüküm değil bir bilgi olarak ele alarak başlayın. Baskı aylardır yüksekse, panik ataklarınız varsa ya da ruh hâliniz sürekli düşükse lütfen bir uzmanla konuşun.'},
         {q:'Stres gerçekten fiziksel belirti yapar mı?',a:'Evet — kas gerginliği, çene sıkma, bozulmuş uyku ve sindirim şikâyetleri yaygındır. Ancak fiziksel belirtiler, bir hekim başka nedenleri dışlamadan asla "sadece stres" varsayılmamalıdır.'}]}},

{ id:'heart', slug:'heart', icon:'heart-pulse', bg:'#fee2e2', fg:'#b91c1c',
  en:{ name:'Heart Health Habits',
    title:'Heart Health Habits Self-Assessment — ShenTechin MED',
    desc:'A free 25-question self-assessment of lifestyle habits associated with cardiovascular health. Educational only — it does not estimate your cardiac risk.',
    lede:'This assessment covers habits, not risk. Real cardiovascular risk scores need your blood pressure, cholesterol, age and blood glucose — numbers a questionnaire cannot supply. What it can do is show which everyday habits are pulling in the wrong direction.',
    measures:['Movement — weekly minutes, sitting time, and how effort feels','What is on the plate: vegetables, salt, fish, red and processed meat, sugary drinks','Nicotine and alcohol, second-hand smoke included','Your numbers — blood pressure, cholesterol, blood sugar, waist, and whether you know them','Sleep, weight and sustained stress, all now scored components of cardiovascular health'],
    who:'Anyone with heart problems in the family, anyone who has not had their blood pressure checked in years, and anyone wanting to know which habit to change first.',
    faq:[{q:'Does this calculate my heart age or cardiac risk?',a:'No — and it deliberately does not. Validated risk calculators need measured blood pressure, cholesterol and blood glucose. Any site that gives you a "heart age" from lifestyle questions alone is guessing.'},
         {q:'I have chest tightness or palpitations. What should I do?',a:'Speak to a doctor about those directly, and do not use this or any online test to interpret them. Sudden or severe chest pain is an emergency — call your local emergency number.'},
         {q:'What is the single most useful thing I can do?',a:'For most people: get your blood pressure measured. It is quick, widely available, and high blood pressure has no symptoms until it has done damage.'}]},
  tr:{ name:'Kalp Sağlığı Alışkanlıkları',
    title:'Kalp Sağlığı Alışkanlıkları Öz-Değerlendirmesi — ShenTechin MED',
    desc:'Kalp-damar sağlığıyla ilişkili yaşam tarzı alışkanlıklarını ölçen ücretsiz 25 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır — kalp riskinizi hesaplamaz.',
    lede:'Bu değerlendirme riski değil alışkanlıkları kapsar. Gerçek kalp-damar risk skorları tansiyonunuzu, kolesterolünüzü, yaşınızı ve kan şekerinizi gerektirir — bir anketin sağlayamayacağı sayılar. Yapabileceği şey, hangi gündelik alışkanlıkların ters yönde çektiğini göstermektir.',
    measures:['Hareketi — haftalık dakikaları, oturma süresini ve eforun nasıl hissettirdiğini','Tabaktakileri: sebze, tuz, balık, kırmızı ve işlenmiş et, şekerli içecek','Nikotin ve alkolü, pasif içicilik dâhil','Sayılarınızı — tansiyon, kolesterol, kan şekeri, bel çevresi ve bunları bilip bilmediğinizi','Uyku, kilo ve süregelen stresi; üçü de artık kalp sağlığının puanlanan bileşenleri'],
    who:'Ailesinde kalp rahatsızlığı olanlar, yıllardır tansiyonunu ölçtürmemiş olanlar ve önce hangi alışkanlığı değiştireceğini bilmek isteyenler.',
    faq:[{q:'Kalp yaşımı veya kalp riskimi hesaplıyor mu?',a:'Hayır — ve bunu bilinçli olarak yapmıyor. Doğrulanmış risk hesaplayıcıları ölçülmüş tansiyon, kolesterol ve kan şekeri ister. Yalnızca yaşam tarzı sorularından "kalp yaşı" veren her site tahmin yürütüyordur.'},
         {q:'Göğsümde sıkışma veya çarpıntı var, ne yapmalıyım?',a:'Bunları doğrudan bir hekimle konuşun; yorumlamak için bu testi ya da herhangi bir çevrimiçi testi kullanmayın. Ani veya şiddetli göğüs ağrısı acil bir durumdur — 112\'yi arayın.'},
         {q:'Yapabileceğim en faydalı tek şey nedir?',a:'Çoğu kişi için: tansiyonunuzu ölçtürün. Hızlı ve her yerde ulaşılabilir; üstelik yüksek tansiyonun zarar verene kadar hiçbir belirtisi olmaz.'}]}},

{ id:'focus', slug:'focus', icon:'crosshair', bg:'#f3e8ff', fg:'#7e22ce',
  en:{ name:'Focus & Attention',
    title:'Focus & Attention Self-Assessment — ShenTechin MED',
    desc:'A free 25-question self-assessment of concentration, task completion and distractibility. Educational only — it is not an ADHD screening.',
    lede:'Difficulty concentrating has many possible causes, and they look alike from the inside. Sleep debt, chronic stress, an environment full of interruptions and ADHD can all produce the same daily experience. This assessment maps the pattern; it does not name the cause.',
    measures:['Sustained attention — how long you hold one task before it slips','Distraction and multitasking: switching, notifications, tabs, the cost of re-entry','Starting and organising — finishing, postponing, keeping track of what is due','The biological substrate: sleep, movement, caffeine, food, daylight','Deep work and recovery — protected blocks and breaks that are actually breaks'],
    who:'Anyone who reads the same paragraph three times, anyone who starts more than they finish, and anyone wondering whether to raise attention difficulties with a clinician.',
    faq:[{q:'Is this an ADHD test?',a:'No. ADHD is diagnosed by a qualified clinician through a structured interview, developmental history and often input from people who know you. No online questionnaire can do that — including this one.'},
         {q:'Then what is it for?',a:'To give you a clearer description of the pattern. If the difficulties are broad, long-standing and affecting work or relationships, that description is a useful thing to bring to an appointment.'},
         {q:'Could it just be sleep?',a:'Very often, yes. Chronic short sleep produces attention problems that closely resemble ADHD. It is worth ruling out first — our sleep assessment is a reasonable starting point.'}]},
  tr:{ name:'Odaklanma ve Dikkat',
    title:'Odaklanma ve Dikkat Öz-Değerlendirmesi — ShenTechin MED',
    desc:'Yoğunlaşmayı, işleri tamamlamayı ve dikkat dağınıklığını ölçen ücretsiz 25 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır — DEHB taraması değildir.',
    lede:'Odaklanma güçlüğünün birçok olası nedeni vardır ve içeriden bakınca hepsi birbirine benzer. Uyku borcu, kronik stres, kesintilerle dolu bir ortam ve DEHB aynı günlük deneyimi üretebilir. Bu değerlendirme örüntüyü çıkarır; nedeni adlandırmaz.',
    measures:['Sürdürülen dikkati — bir işe, kaymadan ne kadar bağlı kalabildiğinizi','Dikkat dağınıklığı ve çoklu görevi: geçişler, bildirimler, sekmeler, geri dönüş maliyeti','Başlatma ve düzeni — bitirmeyi, ertelemeyi, neyin ne zaman gerektiğini takip etmeyi','Biyolojik zemini: uyku, hareket, kafein, beslenme, gün ışığı','Derin çalışma ve toparlanmayı — korunmuş bloklar ve gerçekten mola olan molalar'],
    who:'Aynı paragrafı üç kez okuyanlar, bitirdiğinden fazlasını başlatanlar ve dikkat güçlüklerini bir klinisyene açıp açmamayı düşünenler.',
    faq:[{q:'Bu bir DEHB testi mi?',a:'Hayır. DEHB, yetkin bir klinisyen tarafından yapılandırılmış görüşme, gelişim öyküsü ve çoğu zaman sizi tanıyan kişilerden alınan bilgiyle tanılanır. Hiçbir çevrimiçi anket bunu yapamaz — bu da dâhil.'},
         {q:'Peki ne işe yarıyor?',a:'Örüntüye dair daha net bir tarif vermeye. Güçlükler geniş, uzun süreli ve işinizi ya da ilişkilerinizi etkiliyorsa, bu tarif bir randevuya götürmeye değer bir bilgidir.'},
         {q:'Sadece uykudan olabilir mi?',a:'Çok sık, evet. Kronik kısa uyku, DEHB\'ye epeyce benzeyen dikkat sorunları üretir. Önce onu dışlamakta fayda var — uyku değerlendirmemiz makul bir başlangıç noktası.'}]}},

{ id:'fitness', slug:'fitness', icon:'dumbbell', bg:'#ffedd5', fg:'#c2410c',
  en:{ name:'Physical Condition',
    title:'Physical Condition Self-Assessment — ShenTechin MED',
    desc:'A free 25-question self-assessment of activity level, strength, flexibility and stamina. Educational only, not a fitness test.',
    lede:'You do not need a gym membership or a lab to get a rough sense of your physical condition. How you handle stairs, how long you sit, whether you can reach your toes and how quickly you recover already say most of it.',
    measures:['Aerobic activity, against the WHO target of 150–300 minutes a week','Strength work — frequency, which muscle groups, and whether the load is going up','Everyday movement: steps, active travel, stairs, walking after meals','Sitting time, and how often long blocks of it get broken up','Capacity and recovery — pain, rest days, sleep, and how you handle a hard week'],
    who:'Anyone starting from zero and wanting a baseline, anyone whose activity has quietly dropped off, and anyone deciding where to put limited effort.',
    faq:[{q:'Is this a real fitness test?',a:'No. Real testing measures things — VO₂ max, grip strength, timed movements. This is a self-report on habits and perceived capacity, which is useful for direction but not for numbers.'},
         {q:'I have back pain. Should I still exercise?',a:'Often yes, but get the pain assessed first rather than working around it. Persistent back pain has causes worth identifying, and the right kind of movement depends on which one it is.'},
         {q:'Where should a complete beginner start?',a:'Walking, daily, at a pace where you can still talk. It is the single most underrated intervention in this whole area and requires no equipment.'}]},
  tr:{ name:'Fiziksel Kondisyon',
    title:'Fiziksel Kondisyon Öz-Değerlendirmesi — ShenTechin MED',
    desc:'Aktivite düzeyini, kuvveti, esnekliği ve dayanıklılığı ölçen ücretsiz 25 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır, kondisyon testi değildir.',
    lede:'Fiziksel durumunuza dair kabaca bir fikir edinmek için spor salonu üyeliğine ya da laboratuvara gerek yok. Merdivenle nasıl baş ettiğiniz, ne kadar oturduğunuz, ayak parmaklarınıza uzanıp uzanamadığınız ve ne kadar çabuk toparlandığınız zaten çoğunu söylüyor.',
    measures:['Aerobik hareketi, DSÖ’nün haftada 150–300 dakikalık hedefine göre','Kuvvet çalışmasını — sıklığını, hangi kas gruplarını ve yükün artıp artmadığını','Günlük hareketi: adımlar, aktif ulaşım, merdiven, yemek sonrası yürüyüş','Oturma süresini ve uzun blokların ne sıklıkla bölündüğünü','Kapasite ve toparlanmayı — ağrı, dinlenme günü, uyku ve zor bir haftayı nasıl geçirdiğinizi'],
    who:'Sıfırdan başlayıp bir başlangıç noktası isteyenler, aktivitesi sessizce azalmış olanlar ve sınırlı çabayı nereye koyacağına karar verenler.',
    faq:[{q:'Bu gerçek bir kondisyon testi mi?',a:'Hayır. Gerçek testler ölçüm yapar — VO₂ maks, kavrama kuvveti, süreli hareketler. Bu, alışkanlıklar ve algılanan kapasite üzerine bir öz-bildirimdir; yön için faydalıdır, sayı için değil.'},
         {q:'Sırt ağrım var, yine de egzersiz yapmalı mıyım?',a:'Çoğu zaman evet, ama etrafından dolaşmak yerine önce ağrıyı değerlendirtin. Süregelen sırt ağrısının saptanmaya değer nedenleri vardır ve doğru hareket türü hangisi olduğuna bağlıdır.'},
         {q:'Tam bir yeni başlayan nereden başlamalı?',a:'Yürüyüş — her gün, hâlâ konuşabildiğiniz bir tempoda. Bu alandaki en hafife alınan tek müdahaledir ve hiçbir ekipman gerektirmez.'}]}},

{ id:'immunity', slug:'immunity', icon:'shield', bg:'#ecfccb', fg:'#4d7c0f',
  en:{ name:'Immune Resilience',
    title:'Immune Resilience Self-Assessment — ShenTechin MED',
    desc:'A free 25-question self-assessment of the sleep, nutrition and lifestyle habits behind how often you get ill. Educational only, not an immune test.',
    lede:'"Boosting immunity" is mostly a marketing phrase. What genuinely affects how well your immune system works is unglamorous: sleep, food, movement, stress and not smoking. This assessment checks those, and flags the symptoms that deserve a doctor instead.',
    measures:['Sleep — the one exposure here tested by deliberately infecting volunteers under quarantine','Movement and weight, on the curve where regular and moderate beats hard and occasional','Food and micronutrients: plants, protein, fibre, vitamin D','Sustained stress and social connection','Hygiene, vaccination, tobacco, alcohol and how you use antibiotics'],
    who:'Anyone who feels like they catch everything going around, anyone tired for months without explanation, and anyone about to spend money on supplements.',
    faq:[{q:'Will this measure my immune system?',a:'No. Immune function is measured with blood tests, not questionnaires. This looks only at the habits and symptoms around it.'},
         {q:'Should I take supplements?',a:'For most people eating a varied diet, no — with vitamin D as a common exception depending on where you live and how much sun you get. Ask a doctor rather than a supplement seller.'},
         {q:'I am tired all the time. Is that an immune problem?',a:'It might not be. Persistent fatigue has many possible causes including anaemia, thyroid problems, sleep disorders and depression — most of them treatable once identified. That is a reason to see a doctor, not to buy vitamins.'}]},
  tr:{ name:'Bağışıklık Direnci',
    title:'Bağışıklık Direnci Öz-Değerlendirmesi — ShenTechin MED',
    desc:'Ne sıklıkla hastalandığınızın ardındaki uyku, beslenme ve yaşam tarzı alışkanlıklarını ölçen ücretsiz 25 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır, bağışıklık testi değildir.',
    lede:'"Bağışıklığı güçlendirmek" büyük ölçüde bir pazarlama ifadesidir. Bağışıklık sisteminizin ne kadar iyi çalıştığını gerçekten etkileyen şeyler gösterişsizdir: uyku, beslenme, hareket, stres ve sigara içmemek. Bu değerlendirme bunlara bakar ve bunun yerine hekim gerektiren belirtileri işaretler.',
    measures:['Uykuyu — buradaki, gönüllüler karantinada bilerek enfekte edilerek sınanmış tek maruziyeti','Hareket ve kiloyu; düzenli ve ılımlı olanın sert ve ara sıra olanı yendiği eğride','Beslenme ve mikrobesinleri: bitkiler, protein, lif, D vitamini','Süregelen stresi ve sosyal bağı','Hijyeni, aşılamayı, tütünü, alkolü ve antibiyotiği nasıl kullandığınızı'],
    who:'Etrafta ne dolaşıyorsa kaptığını hisseden, aylardır nedensiz yorgun olan ve takviyeye para harcamak üzere olan herkes.',
    faq:[{q:'Bağışıklık sistemimi ölçecek mi?',a:'Hayır. Bağışıklık işlevi anketle değil kan testleriyle ölçülür. Bu yalnızca etrafındaki alışkanlıklara ve belirtilere bakar.'},
         {q:'Takviye almalı mıyım?',a:'Çeşitli besleniyorsanız çoğu kişi için hayır — yaşadığınız yere ve güneş görme miktarınıza bağlı olarak D vitamini yaygın bir istisnadır. Bunu takviye satan birine değil bir hekime sorun.'},
         {q:'Sürekli yorgunum, bu bir bağışıklık sorunu mu?',a:'Olmayabilir. Süregelen yorgunluğun anemi, tiroid sorunları, uyku bozuklukları ve depresyon dâhil birçok olası nedeni vardır ve çoğu saptandığında tedavi edilebilir. Bu, vitamin almak için değil hekime gitmek için bir gerekçedir.'}]}},

{ id:'tech', slug:'tech', icon:'smartphone', bg:'#e0e7ff', fg:'#3730a3',
  en:{ name:'Digital Balance',
    title:'Digital Balance Self-Assessment — ShenTechin MED',
    desc:'A free 25-question self-assessment of screen habits, reflexive phone checking and how technology affects your sleep and mood. Educational only.',
    lede:'The question is not how many hours you spend on a screen. It is whether you decide when to pick the phone up, and whether you can put it down when you meant to. This assessment looks at the reflex rather than the total.',
    measures:['How much you use screens, and how much of that is reflex rather than choice','Night-time use and what it costs your sleep','Attention at work: switching, notifications, and the cost of getting back in','Social media and mood — comparison, distress, how you feel afterwards','Boundaries and control: whether you can stop once you have decided to'],
    who:'Anyone who opens an app without deciding to, anyone whose evenings disappear, and anyone who suspects their phone is costing them sleep.',
    faq:[{q:'Is this a screen addiction test?',a:'No. Problematic technology use is a real clinical topic but it is assessed by clinicians, not by websites. This describes habits, and it is deliberately more interested in the reflex than the hour count.'},
         {q:'What is the single most effective change?',a:'Charging the phone outside the bedroom. It removes the last hour of the night and the first hour of the morning from the loop at the same time, and needs no willpower after the first week.'},
         {q:'Does screen time really affect sleep?',a:'The evening use matters more through what you do than through the light itself — messages, news and social feeds are activating, and that is harder to switch off than brightness.'}]},
  tr:{ name:'Dijital Denge',
    title:'Dijital Denge Öz-Değerlendirmesi — ShenTechin MED',
    desc:'Ekran alışkanlıklarını, refleks hâline gelmiş telefon kontrolünü ve teknolojinin uykunuzla ruh hâlinize etkisini ölçen ücretsiz 25 soruluk öz-değerlendirme.',
    lede:'Mesele ekran başında kaç saat geçirdiğiniz değil. Telefonu ne zaman eline alacağına sizin karar verip vermediğiniz ve bırakmayı düşündüğünüzde bırakabilip bırakamadığınız. Bu değerlendirme toplamı değil refleksi inceliyor.',
    measures:['Ekranları ne kadar kullandığınızı ve bunun ne kadarının seçim değil refleks olduğunu','Gece kullanımını ve uykunuza maliyetini','İşteki dikkati: geçişler, bildirimler ve geri dönmenin maliyeti','Sosyal medya ve ruh hâlini — karşılaştırma, sıkıntı, sonrasında ne hissettiğiniz','Sınırlar ve kontrolü: karar verdiğinizde durabiliyor musunuz'],
    who:'Karar vermeden uygulama açanlar, akşamları buharlaşanlar ve telefonunun uykusundan çaldığından şüphelenenler.',
    faq:[{q:'Bu bir ekran bağımlılığı testi mi?',a:'Hayır. Sorunlu teknoloji kullanımı gerçek bir klinik konudur ama web siteleri tarafından değil klinisyenler tarafından değerlendirilir. Bu, alışkanlıkları tarif eder ve bilinçli olarak saat sayısından çok refleksle ilgilenir.'},
         {q:'En etkili tek değişiklik nedir?',a:'Telefonu yatak odasının dışında şarj etmek. Gecenin son saatiyle sabahın ilk saatini aynı anda döngüden çıkarır ve ilk haftadan sonra irade gerektirmez.'},
         {q:'Ekran süresi gerçekten uykuyu etkiler mi?',a:'Akşam kullanımı ışığın kendisinden çok ne yaptığınız üzerinden önemlidir — mesajlar, haberler ve sosyal akışlar uyarıcıdır ve bunu kapatmak parlaklığı kısmaktan daha zordur.'}]}}
];
