/* 9 test tanıtım sayfasının içeriği. Her sayfa iki dili de HTML içinde taşır;
   i18n.js yalnızca doğru dildeki bloğu gösterir. */
export const TESTS = [
{ id:'sleep', slug:'sleep', icon:'moon', bg:'#e0f2fe', fg:'#0369a1',
  en:{ name:'Sleep Quality',
    title:'Sleep Quality Self-Assessment — ShenTechin Med',
    desc:'A free 10-question self-assessment of your sleep schedule, environment and bedtime habits. Educational only, not a diagnosis.',
    lede:'Sleep problems rarely have a single cause. More often they are the sum of a bedtime that moves around, a room that is too bright or too warm, and a few habits in the last hour of the day. This assessment walks through those one at a time.',
    measures:['How long you take to fall asleep and how often you wake in the night','Whether you wake up rested, and how much daytime sleepiness you carry','Your bedroom: darkness, temperature, noise and bedding','The last-hour habits — caffeine, screens, heavy meals, late exercise','Signs worth mentioning to a doctor: snoring, breathing pauses, sleep paralysis'],
    who:'Anyone who sleeps enough hours but still wakes up tired, has a bedtime that drifts later each week, or wants a structured way to see which habit is doing the most damage.',
    faq:[{q:'Can this tell me if I have insomnia or sleep apnoea?',a:'No. Both are clinical diagnoses that need a doctor, and sleep apnoea in particular is usually confirmed with a sleep study. What this assessment can do is show you whether the signs are present often enough to be worth raising.'},
         {q:'How long does it take?',a:'The short version is 10 questions and takes about two minutes. The detailed version covers all 25 questions and takes about five.'},
         {q:'Are my answers stored anywhere?',a:'Only in your own browser, so you can leave and come back. Nothing is sent to us and there is no account to create.'}]},
  tr:{ name:'Uyku Kalitesi',
    title:'Uyku Kalitesi Öz-Değerlendirmesi — ShenTechin Med',
    desc:'Uyku düzeninizi, ortamınızı ve yatma saati alışkanlıklarınızı ölçen ücretsiz 10 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır, teşhis değildir.',
    lede:'Uyku sorunlarının tek bir nedeni nadiren olur. Çoğu zaman kayan bir yatış saatinin, fazla aydınlık ya da sıcak bir odanın ve günün son saatindeki birkaç alışkanlığın toplamıdır. Bu değerlendirme bunların üzerinden tek tek geçiyor.',
    measures:['Uykuya dalma sürenizi ve gece kaç kez uyandığınızı','Dinlenmiş uyanıp uyanmadığınızı ve gün içi uyku hâlinizi','Yatak odanızı: karanlık, sıcaklık, gürültü ve yatak düzeni','Son saatteki alışkanlıkları — kafein, ekran, ağır yemek, geç egzersiz','Hekime söylenmeye değer işaretleri: horlama, nefes durması, karabasan'],
    who:'Yeterli saat uyuduğu hâlde yorgun uyanan, yatış saati her hafta biraz daha geriye kayan ya da hangi alışkanlığın en çok zarar verdiğini düzenli biçimde görmek isteyen herkes.',
    faq:[{q:'Bu test uykusuzluk (insomnia) veya uyku apnesi olduğumu söyler mi?',a:'Hayır. İkisi de hekim gerektiren klinik tanılardır; özellikle uyku apnesi genellikle uyku testiyle doğrulanır. Bu değerlendirmenin yapabileceği şey, işaretlerin dile getirmeye değecek sıklıkta olup olmadığını göstermektir.'},
         {q:'Ne kadar sürüyor?',a:'Kısa sürüm 10 soru, yaklaşık iki dakika. Detaylı sürüm 25 sorunun tamamını kapsıyor ve yaklaşık beş dakika sürüyor.'},
         {q:'Cevaplarım bir yerde saklanıyor mu?',a:'Yalnızca kendi tarayıcınızda; böylece ara verip geri dönebiliyorsunuz. Bize hiçbir şey gönderilmiyor ve açılacak bir hesap yok.'}]}},

{ id:'skin', slug:'skin', icon:'sparkles', bg:'#fce7f3', fg:'#be185d',
  en:{ name:'Skin Profile',
    title:'Skin Profile Self-Assessment — ShenTechin Med',
    desc:'A free 10-question self-assessment of your skin type, sun protection and daily routine. Educational only, not a dermatological diagnosis.',
    lede:'Most skincare advice is written for a skin type you may not have. Before choosing products it helps to know how your skin actually behaves — how it reacts to sun, how quickly it gets oily, and how it responds to being touched, washed and covered.',
    measures:['Oiliness, dryness and how your skin feels after washing','Sensitivity: redness, reactions to new products, eczema or rosacea','Sun behaviour and how consistently you use sunscreen','Habits that irritate: over-exfoliating, sleeping in makeup, touching your face','Signs of barrier strain — dullness, roughness, persistent breakouts'],
    who:'Anyone unsure whether their skin is dry or dehydrated, oily or over-cleansed, and anyone who keeps buying products without a clear picture of what their skin actually needs.',
    faq:[{q:'Will this tell me which products to buy?',a:'No, and be sceptical of anything that claims it will from a questionnaire. It gives you a clearer description of how your skin behaves, which makes product advice easier to filter.'},
         {q:'I have acne or rosacea. Is this useful?',a:'As a habit check, yes. As a treatment guide, no — both respond to specific medical treatment, and a dermatologist will get you there far faster than a routine change.'},
         {q:'Does it account for skin tone?',a:'Only indirectly, through how your skin reacts to sun exposure. It is not a substitute for advice tailored to your skin tone.'}]},
  tr:{ name:'Cilt Profili',
    title:'Cilt Profili Öz-Değerlendirmesi — ShenTechin Med',
    desc:'Cilt tipinizi, güneşten korunmanızı ve günlük rutininizi ölçen ücretsiz 10 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır, dermatolojik teşhis değildir.',
    lede:'Cilt bakımı önerilerinin çoğu, sizde olmayan bir cilt tipi için yazılmıştır. Ürün seçmeden önce cildinizin gerçekte nasıl davrandığını bilmek işe yarar — güneşe nasıl tepki verdiğini, ne kadar çabuk yağlandığını, dokunulunca, yıkanınca ve kapatılınca ne yaptığını.',
    measures:['Yağlanma, kuruluk ve yıkandıktan sonra cildinizin hâlini','Hassasiyeti: kızarıklık, yeni ürünlere tepki, egzama veya rozase','Güneş karşısındaki davranışı ve güneş kremini ne kadar düzenli kullandığınızı','Tahriş eden alışkanlıkları: aşırı peeling, makyajla uyumak, yüze dokunmak','Bariyer zorlanması işaretlerini — solgunluk, pütürlülük, geçmeyen sivilce'],
    who:'Cildinin kuru mu susuz mu, yağlı mı aşırı temizlenmiş mi olduğundan emin olmayan ve cildinin gerçekte neye ihtiyacı olduğunu bilmeden ürün almayı sürdüren herkes.',
    faq:[{q:'Hangi ürünleri alacağımı söyleyecek mi?',a:'Hayır — ve bir anketten yola çıkıp bunu vaat eden her şeye kuşkuyla yaklaşın. Size cildinizin nasıl davrandığına dair daha net bir tarif verir; bu da ürün önerilerini elemeyi kolaylaştırır.'},
         {q:'Aknem veya rozasem var. İşe yarar mı?',a:'Alışkanlık kontrolü olarak evet. Tedavi rehberi olarak hayır — ikisi de belirli tıbbi tedaviye yanıt verir ve bir dermatolog sizi oraya rutin değişikliğinden çok daha hızlı götürür.'},
         {q:'Cilt tonunu hesaba katıyor mu?',a:'Yalnızca dolaylı olarak, cildinizin güneşe verdiği tepki üzerinden. Cilt tonunuza özel bir önerinin yerini tutmaz.'}]}},

{ id:'diet', slug:'diet', icon:'leaf', bg:'#dcfce7', fg:'#15803d',
  en:{ name:'Nutrition Habits',
    title:'Nutrition Habits Self-Assessment — ShenTechin Med',
    desc:'A free 10-question self-assessment of meal regularity, food choices and eating patterns. Educational only, not dietary advice.',
    lede:'This is not a diet test and it will not calculate anything about your body. It asks about the structure around your eating — when you eat, what usually ends up on the plate, and what tends to drive the decision.',
    measures:['Meal regularity, skipped meals and late-night eating','Vegetables, fruit, whole grains and how varied your diet is','Processed food, sugary drinks, salt and alcohol','Whether stress, boredom or convenience is driving food choices','Digestion, energy dips and how satisfied you feel after eating'],
    who:'Anyone whose eating has drifted into whatever is quickest, anyone stuck in a start-a-diet-then-abandon-it loop, and anyone who wants to find the one habit worth fixing first.',
    faq:[{q:'Does it calculate calories or BMI?',a:'No. It does not ask for your weight, height or intake, and it does not estimate anything about your body. It only looks at habits.'},
         {q:'Can it detect a food intolerance?',a:'No. Intolerances and allergies need proper testing — self-diagnosis here leads people to cut out foods unnecessarily.'},
         {q:'Should I see a dietitian instead?',a:'If you have a medical condition, a history of disordered eating, or repeated cycles of losing and regaining weight, then yes — a dietitian will help far more than any online assessment.'}]},
  tr:{ name:'Beslenme Alışkanlıkları',
    title:'Beslenme Alışkanlıkları Öz-Değerlendirmesi — ShenTechin Med',
    desc:'Öğün düzeninizi, besin tercihlerinizi ve yeme örüntünüzü ölçen ücretsiz 10 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır, diyet önerisi değildir.',
    lede:'Bu bir diyet testi değildir ve bedeninizle ilgili hiçbir hesap yapmaz. Yemenizin etrafındaki düzeni sorar — ne zaman yediğinizi, tabakta genellikle ne olduğunu ve kararı çoğunlukla neyin verdiğini.',
    measures:['Öğün düzenini, atlanan öğünleri ve gece geç yemeyi','Sebze, meyve, tam tahıl ve beslenmenizin çeşitliliğini','İşlenmiş gıda, şekerli içecek, tuz ve alkolü','Besin seçimini stresin mi, can sıkıntısının mı, pratikliğin mi yönlendirdiğini','Sindirimi, enerji düşüşlerini ve yemekten sonraki tokluk hissini'],
    who:'Yemeği "en hızlı ne varsa" hâline gelmiş olanlar, diyete başlayıp bırakma döngüsüne sıkışanlar ve önce hangi alışkanlığı düzeltmesi gerektiğini bulmak isteyenler.',
    faq:[{q:'Kalori veya VKİ hesaplıyor mu?',a:'Hayır. Kilonuzu, boyunuzu ya da aldığınız miktarı sormuyor ve bedeninizle ilgili hiçbir tahmin yapmıyor. Yalnızca alışkanlıklara bakıyor.'},
         {q:'Besin intoleransı saptayabilir mi?',a:'Hayır. İntoleranslar ve alerjiler düzgün testlerle saptanır — buradan yola çıkarak kendi kendine tanı koymak, insanların gereksiz yere besin kesmesine yol açıyor.'},
         {q:'Bunun yerine diyetisyene mi gitmeliyim?',a:'Bir sağlık sorununuz, düzensiz yeme geçmişiniz ya da tekrarlayan kilo verip alma döngüleriniz varsa evet — bir diyetisyen her çevrimiçi değerlendirmeden çok daha faydalı olur.'}]}},

{ id:'stress', slug:'stress', icon:'brain', bg:'#fef3c7', fg:'#b45309',
  en:{ name:'Stress Load',
    title:'Stress Load Self-Assessment — ShenTechin Med',
    desc:'A free 10-question self-assessment of daily pressure, physical stress signs and recovery capacity. Educational only, not a mental health diagnosis.',
    lede:'Stress becomes a problem less because of how much arrives and more because of how little recovery gets in between. This assessment looks at both sides: the load you carry and what you have in place to offset it.',
    measures:['How often you feel overwhelmed, irritable or out of control','Physical signs: muscle tension, jaw clenching, trouble relaxing','Recovery: hobbies, laughter, people to talk to, time genuinely off','Sources of pressure — work, money, social media, loneliness','Burnout signs and how long they have been present'],
    who:'Anyone who feels permanently switched on, anyone whose body has started keeping the score, and anyone wanting a structured look before deciding whether to get help.',
    faq:[{q:'Is this a depression or anxiety screening?',a:'No. Those are specific clinical screenings, and this is not one of them. If your answers concern you, that is a good reason to speak to a GP or psychologist rather than to retake the test.'},
         {q:'I scored badly. What now?',a:'Start by treating it as information rather than a verdict. If pressure has been high for months, if you have panic attacks, or if your mood has been consistently low, please talk to a professional.'},
         {q:'Can stress really cause physical symptoms?',a:'Yes — muscle tension, jaw clenching, disturbed sleep and digestive upset are all common. But physical symptoms should never be assumed to be "just stress" without a doctor ruling out other causes.'}]},
  tr:{ name:'Stres Yükü',
    title:'Stres Yükü Öz-Değerlendirmesi — ShenTechin Med',
    desc:'Günlük baskıyı, fiziksel stres işaretlerini ve toparlanma kapasitesini ölçen ücretsiz 10 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır, ruh sağlığı teşhisi değildir.',
    lede:'Stres, ne kadar geldiğinden çok arasına ne kadar az toparlanma girdiği için sorun hâline gelir. Bu değerlendirme iki tarafa da bakıyor: taşıdığınız yüke ve onu dengelemek için elinizde ne olduğuna.',
    measures:['Ne sıklıkla bunalmış, sinirli ya da kontrolü kaybetmiş hissettiğinizi','Fiziksel işaretleri: kas gerginliği, çene sıkma, gevşeyememe','Toparlanmayı: hobiler, gülmek, konuşacak insanlar, gerçekten boş zaman','Baskı kaynaklarını — iş, para, sosyal medya, yalnızlık','Tükenmişlik işaretlerini ve ne zamandır sürdüğünü'],
    who:'Sürekli "açık" hisseden, bedeni hesabı tutmaya başlamış olan ve destek alıp almayacağına karar vermeden önce düzenli bir bakış isteyen herkes.',
    faq:[{q:'Bu bir depresyon veya anksiyete taraması mı?',a:'Hayır. Onlar belirli klinik taramalardır, bu onlardan biri değildir. Cevaplarınız sizi endişelendiriyorsa, bu testi tekrar çözmek yerine bir hekime ya da psikoloğa danışmak için iyi bir gerekçedir.'},
         {q:'Düşük puan aldım, şimdi ne olacak?',a:'Bunu bir hüküm değil bir bilgi olarak ele alarak başlayın. Baskı aylardır yüksekse, panik ataklarınız varsa ya da ruh hâliniz sürekli düşükse lütfen bir uzmanla konuşun.'},
         {q:'Stres gerçekten fiziksel belirti yapar mı?',a:'Evet — kas gerginliği, çene sıkma, bozulmuş uyku ve sindirim şikâyetleri yaygındır. Ancak fiziksel belirtiler, bir hekim başka nedenleri dışlamadan asla "sadece stres" varsayılmamalıdır.'}]}},

{ id:'heart', slug:'heart', icon:'heart-pulse', bg:'#fee2e2', fg:'#b91c1c',
  en:{ name:'Heart Health Habits',
    title:'Heart Health Habits Self-Assessment — ShenTechin Med',
    desc:'A free 10-question self-assessment of lifestyle habits associated with cardiovascular health. Educational only — it does not estimate your cardiac risk.',
    lede:'This assessment covers habits, not risk. Real cardiovascular risk scores need your blood pressure, cholesterol, age and blood glucose — numbers a questionnaire cannot supply. What it can do is show which everyday habits are pulling in the wrong direction.',
    measures:['Aerobic activity and how easily you get out of breath','Diet factors: fried food, salt, sugar, alcohol, fish and omega-3','Smoking, long sitting hours and short sleep','Whether you know and track your blood pressure and cholesterol','Family history and symptoms that need a doctor rather than a quiz'],
    who:'Anyone with heart problems in the family, anyone who has not had their blood pressure checked in years, and anyone wanting to know which habit to change first.',
    faq:[{q:'Does this calculate my heart age or cardiac risk?',a:'No — and it deliberately does not. Validated risk calculators need measured blood pressure, cholesterol and blood glucose. Any site that gives you a "heart age" from lifestyle questions alone is guessing.'},
         {q:'I have chest tightness or palpitations. What should I do?',a:'Speak to a doctor about those directly, and do not use this or any online test to interpret them. Sudden or severe chest pain is an emergency — call your local emergency number.'},
         {q:'What is the single most useful thing I can do?',a:'For most people: get your blood pressure measured. It is quick, widely available, and high blood pressure has no symptoms until it has done damage.'}]},
  tr:{ name:'Kalp Sağlığı Alışkanlıkları',
    title:'Kalp Sağlığı Alışkanlıkları Öz-Değerlendirmesi — ShenTechin Med',
    desc:'Kalp-damar sağlığıyla ilişkili yaşam tarzı alışkanlıklarını ölçen ücretsiz 10 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır — kalp riskinizi hesaplamaz.',
    lede:'Bu değerlendirme riski değil alışkanlıkları kapsar. Gerçek kalp-damar risk skorları tansiyonunuzu, kolesterolünüzü, yaşınızı ve kan şekerinizi gerektirir — bir anketin sağlayamayacağı sayılar. Yapabileceği şey, hangi gündelik alışkanlıkların ters yönde çektiğini göstermektir.',
    measures:['Aerobik aktiviteyi ve ne kadar çabuk nefes nefese kaldığınızı','Beslenme etkenlerini: kızartma, tuz, şeker, alkol, balık ve omega-3','Sigarayı, uzun oturma saatlerini ve kısa uykuyu','Tansiyon ve kolesterolünüzü bilip takip edip etmediğinizi','Aile öyküsünü ve test değil hekim gerektiren belirtileri'],
    who:'Ailesinde kalp rahatsızlığı olanlar, yıllardır tansiyonunu ölçtürmemiş olanlar ve önce hangi alışkanlığı değiştireceğini bilmek isteyenler.',
    faq:[{q:'Kalp yaşımı veya kalp riskimi hesaplıyor mu?',a:'Hayır — ve bunu bilinçli olarak yapmıyor. Doğrulanmış risk hesaplayıcıları ölçülmüş tansiyon, kolesterol ve kan şekeri ister. Yalnızca yaşam tarzı sorularından "kalp yaşı" veren her site tahmin yürütüyordur.'},
         {q:'Göğsümde sıkışma veya çarpıntı var, ne yapmalıyım?',a:'Bunları doğrudan bir hekimle konuşun; yorumlamak için bu testi ya da herhangi bir çevrimiçi testi kullanmayın. Ani veya şiddetli göğüs ağrısı acil bir durumdur — 112\'yi arayın.'},
         {q:'Yapabileceğim en faydalı tek şey nedir?',a:'Çoğu kişi için: tansiyonunuzu ölçtürün. Hızlı ve her yerde ulaşılabilir; üstelik yüksek tansiyonun zarar verene kadar hiçbir belirtisi olmaz.'}]}},

{ id:'focus', slug:'focus', icon:'crosshair', bg:'#f3e8ff', fg:'#7e22ce',
  en:{ name:'Focus & Attention',
    title:'Focus & Attention Self-Assessment — ShenTechin Med',
    desc:'A free 10-question self-assessment of concentration, task completion and distractibility. Educational only — it is not an ADHD screening.',
    lede:'Difficulty concentrating has many possible causes, and they look alike from the inside. Sleep debt, chronic stress, an environment full of interruptions and ADHD can all produce the same daily experience. This assessment maps the pattern; it does not name the cause.',
    measures:['Holding attention on a task and finishing what you start','How easily you are pulled away, and how long it takes to return','Organisation, time management and remembering commitments','Restlessness, impulsivity and racing thoughts','Mental fatigue and how much of it tracks your sleep'],
    who:'Anyone who reads the same paragraph three times, anyone who starts more than they finish, and anyone wondering whether to raise attention difficulties with a clinician.',
    faq:[{q:'Is this an ADHD test?',a:'No. ADHD is diagnosed by a qualified clinician through a structured interview, developmental history and often input from people who know you. No online questionnaire can do that — including this one.'},
         {q:'Then what is it for?',a:'To give you a clearer description of the pattern. If the difficulties are broad, long-standing and affecting work or relationships, that description is a useful thing to bring to an appointment.'},
         {q:'Could it just be sleep?',a:'Very often, yes. Chronic short sleep produces attention problems that closely resemble ADHD. It is worth ruling out first — our sleep assessment is a reasonable starting point.'}]},
  tr:{ name:'Odaklanma ve Dikkat',
    title:'Odaklanma ve Dikkat Öz-Değerlendirmesi — ShenTechin Med',
    desc:'Yoğunlaşmayı, işleri tamamlamayı ve dikkat dağınıklığını ölçen ücretsiz 10 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır — DEHB taraması değildir.',
    lede:'Odaklanma güçlüğünün birçok olası nedeni vardır ve içeriden bakınca hepsi birbirine benzer. Uyku borcu, kronik stres, kesintilerle dolu bir ortam ve DEHB aynı günlük deneyimi üretebilir. Bu değerlendirme örüntüyü çıkarır; nedeni adlandırmaz.',
    measures:['Bir işte dikkati tutmayı ve başladığınızı bitirmeyi','Ne kadar kolay koptuğunuzu ve geri dönmenin ne kadar sürdüğünü','Düzeni, zaman yönetimini ve sorumlulukları hatırlamayı','Yerinde duramama, dürtüsellik ve yarışan düşünceleri','Zihinsel yorgunluğu ve bunun ne kadarının uykuyla ilerlediğini'],
    who:'Aynı paragrafı üç kez okuyanlar, bitirdiğinden fazlasını başlatanlar ve dikkat güçlüklerini bir klinisyene açıp açmamayı düşünenler.',
    faq:[{q:'Bu bir DEHB testi mi?',a:'Hayır. DEHB, yetkin bir klinisyen tarafından yapılandırılmış görüşme, gelişim öyküsü ve çoğu zaman sizi tanıyan kişilerden alınan bilgiyle tanılanır. Hiçbir çevrimiçi anket bunu yapamaz — bu da dâhil.'},
         {q:'Peki ne işe yarıyor?',a:'Örüntüye dair daha net bir tarif vermeye. Güçlükler geniş, uzun süreli ve işinizi ya da ilişkilerinizi etkiliyorsa, bu tarif bir randevuya götürmeye değer bir bilgidir.'},
         {q:'Sadece uykudan olabilir mi?',a:'Çok sık, evet. Kronik kısa uyku, DEHB\'ye epeyce benzeyen dikkat sorunları üretir. Önce onu dışlamakta fayda var — uyku değerlendirmemiz makul bir başlangıç noktası.'}]}},

{ id:'fitness', slug:'fitness', icon:'dumbbell', bg:'#ffedd5', fg:'#c2410c',
  en:{ name:'Physical Condition',
    title:'Physical Condition Self-Assessment — ShenTechin Med',
    desc:'A free 10-question self-assessment of activity level, strength, flexibility and stamina. Educational only, not a fitness test.',
    lede:'You do not need a gym membership or a lab to get a rough sense of your physical condition. How you handle stairs, how long you sit, whether you can reach your toes and how quickly you recover already say most of it.',
    measures:['How often you exercise and what kind','Everyday capacity: stairs, walking pace, breathlessness','Strength, core stability and how quickly you recover','Flexibility, balance and posture','Sitting hours and how much they break up your day'],
    who:'Anyone starting from zero and wanting a baseline, anyone whose activity has quietly dropped off, and anyone deciding where to put limited effort.',
    faq:[{q:'Is this a real fitness test?',a:'No. Real testing measures things — VO₂ max, grip strength, timed movements. This is a self-report on habits and perceived capacity, which is useful for direction but not for numbers.'},
         {q:'I have back pain. Should I still exercise?',a:'Often yes, but get the pain assessed first rather than working around it. Persistent back pain has causes worth identifying, and the right kind of movement depends on which one it is.'},
         {q:'Where should a complete beginner start?',a:'Walking, daily, at a pace where you can still talk. It is the single most underrated intervention in this whole area and requires no equipment.'}]},
  tr:{ name:'Fiziksel Kondisyon',
    title:'Fiziksel Kondisyon Öz-Değerlendirmesi — ShenTechin Med',
    desc:'Aktivite düzeyini, kuvveti, esnekliği ve dayanıklılığı ölçen ücretsiz 10 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır, kondisyon testi değildir.',
    lede:'Fiziksel durumunuza dair kabaca bir fikir edinmek için spor salonu üyeliğine ya da laboratuvara gerek yok. Merdivenle nasıl baş ettiğiniz, ne kadar oturduğunuz, ayak parmaklarınıza uzanıp uzanamadığınız ve ne kadar çabuk toparlandığınız zaten çoğunu söylüyor.',
    measures:['Ne sıklıkla ve ne tür egzersiz yaptığınızı','Gündelik kapasiteyi: merdiven, yürüyüş temposu, nefes darlığı','Kuvveti, gövde stabilitesini ve toparlanma hızını','Esnekliği, dengeyi ve duruşu','Oturma saatlerini ve gününüzü ne kadar böldüğünüzü'],
    who:'Sıfırdan başlayıp bir başlangıç noktası isteyenler, aktivitesi sessizce azalmış olanlar ve sınırlı çabayı nereye koyacağına karar verenler.',
    faq:[{q:'Bu gerçek bir kondisyon testi mi?',a:'Hayır. Gerçek testler ölçüm yapar — VO₂ maks, kavrama kuvveti, süreli hareketler. Bu, alışkanlıklar ve algılanan kapasite üzerine bir öz-bildirimdir; yön için faydalıdır, sayı için değil.'},
         {q:'Sırt ağrım var, yine de egzersiz yapmalı mıyım?',a:'Çoğu zaman evet, ama etrafından dolaşmak yerine önce ağrıyı değerlendirtin. Süregelen sırt ağrısının saptanmaya değer nedenleri vardır ve doğru hareket türü hangisi olduğuna bağlıdır.'},
         {q:'Tam bir yeni başlayan nereden başlamalı?',a:'Yürüyüş — her gün, hâlâ konuşabildiğiniz bir tempoda. Bu alandaki en hafife alınan tek müdahaledir ve hiçbir ekipman gerektirmez.'}]}},

{ id:'immunity', slug:'immunity', icon:'shield', bg:'#ecfccb', fg:'#4d7c0f',
  en:{ name:'Immune Resilience',
    title:'Immune Resilience Self-Assessment — ShenTechin Med',
    desc:'A free 10-question self-assessment of the sleep, nutrition and lifestyle habits behind how often you get ill. Educational only, not an immune test.',
    lede:'"Boosting immunity" is mostly a marketing phrase. What genuinely affects how well your immune system works is unglamorous: sleep, food, movement, stress and not smoking. This assessment checks those, and flags the symptoms that deserve a doctor instead.',
    measures:['How often you get ill and how long recovery takes','Sleep, nutrition and regular movement','Smoking, alcohol and chronic stress','Persistent fatigue, slow healing and digestive issues','Known allergies, autoimmune conditions and vaccination habits'],
    who:'Anyone who feels like they catch everything going around, anyone tired for months without explanation, and anyone about to spend money on supplements.',
    faq:[{q:'Will this measure my immune system?',a:'No. Immune function is measured with blood tests, not questionnaires. This looks only at the habits and symptoms around it.'},
         {q:'Should I take supplements?',a:'For most people eating a varied diet, no — with vitamin D as a common exception depending on where you live and how much sun you get. Ask a doctor rather than a supplement seller.'},
         {q:'I am tired all the time. Is that an immune problem?',a:'It might not be. Persistent fatigue has many possible causes including anaemia, thyroid problems, sleep disorders and depression — most of them treatable once identified. That is a reason to see a doctor, not to buy vitamins.'}]},
  tr:{ name:'Bağışıklık Direnci',
    title:'Bağışıklık Direnci Öz-Değerlendirmesi — ShenTechin Med',
    desc:'Ne sıklıkla hastalandığınızın ardındaki uyku, beslenme ve yaşam tarzı alışkanlıklarını ölçen ücretsiz 10 soruluk öz-değerlendirme. Bilgilendirme amaçlıdır, bağışıklık testi değildir.',
    lede:'"Bağışıklığı güçlendirmek" büyük ölçüde bir pazarlama ifadesidir. Bağışıklık sisteminizin ne kadar iyi çalıştığını gerçekten etkileyen şeyler gösterişsizdir: uyku, beslenme, hareket, stres ve sigara içmemek. Bu değerlendirme bunlara bakar ve bunun yerine hekim gerektiren belirtileri işaretler.',
    measures:['Ne sıklıkla hastalandığınızı ve toparlanmanın ne kadar sürdüğünü','Uykuyu, beslenmeyi ve düzenli hareketi','Sigarayı, alkolü ve kronik stresi','Süregelen yorgunluğu, geç iyileşmeyi ve sindirim sorunlarını','Bilinen alerjileri, otoimmün hastalıkları ve aşı alışkanlıklarını'],
    who:'Etrafta ne dolaşıyorsa kaptığını hisseden, aylardır nedensiz yorgun olan ve takviyeye para harcamak üzere olan herkes.',
    faq:[{q:'Bağışıklık sistemimi ölçecek mi?',a:'Hayır. Bağışıklık işlevi anketle değil kan testleriyle ölçülür. Bu yalnızca etrafındaki alışkanlıklara ve belirtilere bakar.'},
         {q:'Takviye almalı mıyım?',a:'Çeşitli besleniyorsanız çoğu kişi için hayır — yaşadığınız yere ve güneş görme miktarınıza bağlı olarak D vitamini yaygın bir istisnadır. Bunu takviye satan birine değil bir hekime sorun.'},
         {q:'Sürekli yorgunum, bu bir bağışıklık sorunu mu?',a:'Olmayabilir. Süregelen yorgunluğun anemi, tiroid sorunları, uyku bozuklukları ve depresyon dâhil birçok olası nedeni vardır ve çoğu saptandığında tedavi edilebilir. Bu, vitamin almak için değil hekime gitmek için bir gerekçedir.'}]}},

{ id:'tech', slug:'tech', icon:'smartphone', bg:'#e0e7ff', fg:'#3730a3',
  en:{ name:'Digital Balance',
    title:'Digital Balance Self-Assessment — ShenTechin Med',
    desc:'A free 10-question self-assessment of screen habits, reflexive phone checking and how technology affects your sleep and mood. Educational only.',
    lede:'The question is not how many hours you spend on a screen. It is whether you decide when to pick the phone up, and whether you can put it down when you meant to. This assessment looks at the reflex rather than the total.',
    measures:['Reflexive checking — first thing in the morning, during meals, mid-conversation','Whether you can watch, read or rest without reaching for the phone','Screens near bedtime and their effect on your sleep','Physical effects: eye strain, neck pain, phantom vibrations','How much your mood tracks what happens on a screen'],
    who:'Anyone who opens an app without deciding to, anyone whose evenings disappear, and anyone who suspects their phone is costing them sleep.',
    faq:[{q:'Is this a screen addiction test?',a:'No. Problematic technology use is a real clinical topic but it is assessed by clinicians, not by websites. This describes habits, and it is deliberately more interested in the reflex than the hour count.'},
         {q:'What is the single most effective change?',a:'Charging the phone outside the bedroom. It removes the last hour of the night and the first hour of the morning from the loop at the same time, and needs no willpower after the first week.'},
         {q:'Does screen time really affect sleep?',a:'The evening use matters more through what you do than through the light itself — messages, news and social feeds are activating, and that is harder to switch off than brightness.'}]},
  tr:{ name:'Dijital Denge',
    title:'Dijital Denge Öz-Değerlendirmesi — ShenTechin Med',
    desc:'Ekran alışkanlıklarını, refleks hâline gelmiş telefon kontrolünü ve teknolojinin uykunuzla ruh hâlinize etkisini ölçen ücretsiz 10 soruluk öz-değerlendirme.',
    lede:'Mesele ekran başında kaç saat geçirdiğiniz değil. Telefonu ne zaman eline alacağına sizin karar verip vermediğiniz ve bırakmayı düşündüğünüzde bırakabilip bırakamadığınız. Bu değerlendirme toplamı değil refleksi inceliyor.',
    measures:['Refleks kontrolleri — sabah ilk iş, yemekte, konuşmanın ortasında','Telefona uzanmadan izleyip okuyup dinlenebilip dinlenemediğinizi','Yatma saatine yakın ekranları ve uykunuza etkisini','Fiziksel etkileri: göz yorgunluğu, boyun ağrısı, hayali titreşim','Ruh hâlinizin ekranda olan bitene ne kadar bağlı olduğunu'],
    who:'Karar vermeden uygulama açanlar, akşamları buharlaşanlar ve telefonunun uykusundan çaldığından şüphelenenler.',
    faq:[{q:'Bu bir ekran bağımlılığı testi mi?',a:'Hayır. Sorunlu teknoloji kullanımı gerçek bir klinik konudur ama web siteleri tarafından değil klinisyenler tarafından değerlendirilir. Bu, alışkanlıkları tarif eder ve bilinçli olarak saat sayısından çok refleksle ilgilenir.'},
         {q:'En etkili tek değişiklik nedir?',a:'Telefonu yatak odasının dışında şarj etmek. Gecenin son saatiyle sabahın ilk saatini aynı anda döngüden çıkarır ve ilk haftadan sonra irade gerektirmez.'},
         {q:'Ekran süresi gerçekten uykuyu etkiler mi?',a:'Akşam kullanımı ışığın kendisinden çok ne yaptığınız üzerinden önemlidir — mesajlar, haberler ve sosyal akışlar uyarıcıdır ve bunu kapatmak parlaklığı kısmaktan daha zordur.'}]}}
];
